source("./code/data_merge_functions.R")

 dm_overall <- parent_created %>%
  summarise(
    nb_sites = n(),
    idp_hhs = sum(idp_hhs,na.rm = T),
    idp_indvl =sum(idp_indvl,na.rm = T),
    prolonged_hhs = sum(prolonged_hhs,na.rm = T),
    prolonged_indvl = sum(prolonged_indvl,na.rm = T),
    protracted_hhs = sum(protracted_hhs,na.rm = T),
    protracted_indvl = sum(protracted_indvl, na.rm = T),
    refugee_hhs = sum(refugee_hhs,na.rm = T),
    refugee_indvl = sum(refugee_indvl,na.rm = T),
    returnee_hhs = sum(returnee_hhs,na.rm = T),
    returnee_indvl = sum(returnee_indvl,na.rm = T),
    economic_hhs = sum(economic_hhs,na.rm = T),
    economic_indvl = sum(economic_indvl, na.rm = T),
    nomad_hhs = sum(nomad_hhs, na.rm = T),
    nomad_indvl = sum(nomad_indvl, na.rm = T),
    host_hhs = sum(host_hhs, na.rm = T),
    host_indvl = sum(host_indvl, na.rm = T),
    iset_population_discrete = percent_response(iset_population,.,"discrete"),
    iset_population_mixed = percent_response(iset_population,.,"mixed"),
    location_urban = percent_response(location_fs,.,"urban"),
    location_suburban = percent_response(location_fs,.,"suburban"),
    location_rural = percent_response(location_fs,.,"rural"),
    idp_mixed = round(mean(idp_mixed,na.rm = T)*100,2),
    idp_discrete = round(mean(idp_discrete,na.rm = T)*100,2),
    prolong_mixed = round(mean(prolong_mixed,na.rm = T)*100,2),
    prolong_discrete= round(mean(prolong_discrete,na.rm = T)*100,2),
    protract_mixed=round(mean(protract_mixed,na.rm = T)*100,2),
    protract_discrete=mean(protract_discrete,na.rm = T)*100,
    refugee_mixed= round(mean(refugee_mixed,na.rm = T)*100,2),
    refugee_discrete=mean(refugee_discrete,na.rm = T)*100,
    returnee_mixed=round(mean(returnee_mixed,na.rm = T)*100,2),
    returnee_discrete=round(mean(returnee_discrete,na.rm = T)*100,2),
    economic_mixed=round(mean(economic_mixed,na.rm = T)*100,2),
    economic_discrete=round(mean(economic_discrete,na.rm = T)*100,2),
    nomad_mixed=round(mean(nomad_mixed,na.rm = T)*100,2),
    nomad_discrete=round(mean(nomad_discrete,na.rm = T)*100,2),
    migrant_population.idp = round(mean(migrant_population.idp,na.rm = T)*100,2),
    migrant_population.prolong = round(mean(migrant_population.prolong,na.rm = T)*100,2),
    migrant_population.protract = round(mean(migrant_population.protract,na.rm = T)*100,2),
    migrant_population.refugee = round(mean(migrant_population.refugee,na.rm = T)*100,2),
    migrant_population.returnee = round(mean(migrant_population.returnee,na.rm = T)*100,2),
    relocate_plan_yes = percent_response(relocate_plan,.,"yes"),
    relocate_plan_no = percent_response(relocate_plan,.,"no"),
    relocate_plan_dk = percent_response(relocate_plan,.,"dont_know"),
    relocate_pushpull_1_label = select_percents(relocate_pushpull,1,.,questions,choices,"label"),
    relocate_pushpull_1_pct = select_percents(relocate_pushpull,1,.,questions,choices,"percent"),
    relocate_pushpull_2_label = select_percents(relocate_pushpull,2,.,questions,choices,"label"),
    relocate_pushpull_2_pct = select_percents(relocate_pushpull,2,.,questions,choices,"percent"),
    relocate_pushpull_3_label = select_percents(relocate_pushpull,3,.,questions,choices,"label"),
    relocate_pushpull_3_pct = select_percents(relocate_pushpull,3,.,questions,choices,"percent"),
    five_years_yes = percent_response(five_years,.,"yes"),
    five_years_no = percent_response(five_years,.,"no"),
    five_years_dk = percent_response(five_years,.,"dont_know"),
    idp_3mo_hhs = sum(idp_3mo_hhs,na.rm = T),
    idp_prov_origin_1_label = select_percents(idp_prov_origin,1,.,questions,choices,"label"),
    idp_prov_origin_1_pct = select_percents(idp_prov_origin,1,.,questions,choices,"percent"),
    idp_prov_origin_2_label = select_percents(idp_prov_origin,2,.,questions,choices,"label"),
    idp_prov_origin_2_pct = select_percents(idp_prov_origin,2,.,questions,choices,"percent"),
    idp_prov_origin_3_label = select_percents(idp_prov_origin,3,.,questions,choices,"label"),
    idp_prov_origin_3_pct = select_percents(idp_prov_origin,3,.,questions,choices,"percent"),
    returnee_3mo_hhs = sum(returnee_3mo_hhs,na.rm = T),
    returnee_origin_1_label = select_percents(returnee_origin,1,.,questions,choices,"label"),
    returnee_origin_1_pct = select_percents(returnee_origin,1,.,questions,choices,"percent"),
    returnee_origin_2_label = select_percents(returnee_origin,2,.,questions,choices,"label"),
    returnee_origin_2_pct = select_percents(returnee_origin,2,.,questions,choices,"percent"),
    returnee_origin_3_label = select_percents(returnee_origin,3,.,questions,choices,"label"),
    returnee_origin_3_pct = select_percents(returnee_origin,3,.,questions,choices,"percent"),
    shelter_type_1_label = select_percents(shelter_type,1,.,questions,choices,"label"),
    shelter_type_1_pct = select_percents(shelter_type,1,.,questions,choices,"percent"),
    shelter_type_2_label = select_percents(shelter_type,2,.,questions,choices,"label"),
    shelter_type_2_pct = select_percents(shelter_type,2,.,questions,choices,"percent"),
    shelter_type_3_label = select_percents(shelter_type,3,.,questions,choices,"label"),
    shelter_type_3_pct = select_percents(shelter_type,3,.,questions,choices,"percent"),
    tenure_insecure = percent_response(tenure_insecure,.,"yes"),
    hh_rooms = mean(hh_rooms,na.rm = T),
    accom_1_label = select_percents(accom,1,.,questions,choices,"label"),
    accom_1_pct = select_percents(accom,1,.,questions,choices,"percent"),
    accom_2_label = select_percents(accom,2,.,questions,choices,"label"),
    accom_2_pct = select_percents(accom,2,.,questions,choices,"percent"),
    accom_3_label = select_percents(accom,3,.,questions,choices,"label"),
    accom_3_pct = select_percents(accom,3,.,questions,choices,"percent"),
    host_relation_positive = percent_response(host_relation,.,"positive"),
    host_relation_neutral = percent_response(host_relation,.,"neutral"),
    host_relation_negative = percent_response(host_relation,.,"negative"),
    host_relation_prefer_not = percent_response(host_relation,.,"prefer_not"),
    eviction_threat_yes = percent_response(eviction_threat,.,"yes"),
    eviction_threat_no = percent_response(eviction_threat,.,"no"),
    eviction_threat_dk = percent_response(eviction_threat,.,"dont_know"),
    eviction_threat_local_auth = round(mean(eviction_threat_why.local_auth,na.rm = T)*100,2),
    eviction_threat_gvt = round(mean(eviction_threat_why.government,na.rm = T)*100,2),
    eviction_threat_local_host_comm = round(mean(eviction_threat_why.host_comm,na.rm = T)*100,2),
    eviction_threat_local_ot = round(mean(eviction_threat_why.other,na.rm = T)*100,2),
    comm_represent_yes = percent_response(comm_represent,.,"yes"),
    comm_represent_no = percent_response(comm_represent,.,"no"),
    comm_represent_dk = percent_response(comm_represent,.,"dont_know"),
    relocation_yes = percent_response(relocation,.,"yes"),
    relocation_no = percent_response(relocation,.,"no"),
    site_land_yes = percent_response(site_land,.,"yes"),
    site_land_no = percent_response(site_land,.,"no"),
    site_land_dk = percent_response(site_land,.,"dont_know"),
    site_land_owner_gvt = percent_response(site_land_owner,.,"government"),
    site_land_owner_prv = percent_response(site_land_owner,.,"private"),
    site_land_owner_un = percent_response(site_land_owner,.,"un"),
    site_land_owner_common = percent_response(site_land_owner,.,"common"),
    site_land_owner_ot = percent_response(site_land_owner,.,"other"),
    water_distance_fs = percent_response(water_distance_fs,.,"yes"),
    water_source_fs = mean(water_source_fs,na.rm = T),
    water_barrier_1_label = select_percents(water_barrier,1,.,questions,choices,"label"),
    water_barrier_1_pct = select_percents(water_barrier,1,.,questions,choices,"percent"),
    water_barrier_2_label = select_percents(water_barrier,2,.,questions,choices,"label"),
    water_barrier_2_pct = select_percents(water_barrier,2,.,questions,choices,"percent"),
    water_barrier_3_label = select_percents(water_barrier,3,.,questions,choices,"label"),
    water_barrier_3_pct = select_percents(water_barrier,3,.,questions,choices,"percent"),
    health_distance_fs = percent_response(health_distance_fs,.,"yes"),
    health_satisfy_constraint_yes = percent_response(health_satisfy_constraint,.,"yes"),
    health_satisfy_constraint_no = percent_response(health_satisfy_constraint,.,"no"),
    health_satisfy_constraint_dk = percent_response(health_satisfy_constraint,.,"dont_know"),
    health_unsatisfy_constraint.crowded = round(mean(health_unsatisfy_constraint.crowded,na.rm = T)*100,2),
    health_unsatisfy_constraint.hours = round(mean(health_unsatisfy_constraint.hours,na.rm = T)*100,2),
    health_unsatisfy_constraint.expensive = round(mean(health_unsatisfy_constraint.expensive,na.rm = T)*100,2),
    health_unsatisfy_constraint.drug_unavail = round(mean(health_unsatisfy_constraint.drug_unavail,na.rm = T)*100,2),
    health_unsatisfy_constraint.staff_behave = round(mean(health_unsatisfy_constraint.staff_behave,na.rm = T)*100,2),
    health_unsatisfy_constraint.other = round(mean(health_unsatisfy_constraint.other,na.rm = T)*100,2),
    health_unsatisfy_constraint.dont_know = round(mean(health_unsatisfy_constraint.dont_know,na.rm = T)*100,2),
    mhpss_aware_yes = percent_response(mhpss_aware,.,"yes"),
    mhpss_aware_no = percent_response(mhpss_aware,.,"no"),
    mhpss_aware_dk = percent_response(mhpss_aware,.,"dont_know"),
    health_barrier_1_label = select_percents(health_barrier,1,.,questions,choices,"label"),
    health_barrier_1_pct = select_percents(health_barrier,1,.,questions,choices,"percent"),
    health_barrier_2_label = select_percents(health_barrier,2,.,questions,choices,"label"),
    health_barrier_2_pct = select_percents(health_barrier,2,.,questions,choices,"percent"),
    health_barrier_3_label = select_percents(health_barrier,3,.,questions,choices,"label"),
    health_barrier_3_pct = select_percents(health_barrier,3,.,questions,choices,"percent"),
    safe_likert_verygood = percent_response(safe_likert,.,"very_good"),
    safe_likert_good = percent_response(safe_likert,.,"good"),
    safe_likert_neutral = percent_response(safe_likert,.,"neutral"),
    safe_likert_poor = percent_response(safe_likert,.,"poor_qual"),
    safe_likert_verypoor = percent_response(safe_likert,.,"very_poor"),
    move_free_m_yes = percent_response(move_free_m,.,"yes"),
    move_free_m_no = percent_response(move_free_m,.,"no"),
    move_free_m_dk = percent_response(move_free_m,.,"dont_know"),
    move_why_m_1_label = select_percents(move_why_m,1,.,questions,choices,"label"),
    move_why_m_1_pct = select_percents(move_why_m,1,.,questions,choices,"percent"),
    move_why_m_2_label = select_percents(move_why_m,2,.,questions,choices,"label"),
    move_why_m_2_pct = select_percents(move_why_m,2,.,questions,choices,"percent"),
    move_why_m_3_label = select_percents(move_why_m,3,.,questions,choices,"label"),
    move_why_m_3_pct = select_percents(move_why_m,3,.,questions,choices,"percent"),
    move_free_f_yes = percent_response(move_free_f,.,"yes"),
    move_free_f_no = percent_response(move_free_f,.,"no"),
    move_free_f_dk = percent_response(move_free_f,.,"dont_know"),
    move_why_f_1_label = select_percents(move_why_f,1,.,questions,choices,"label"),
    move_why_f_1_pct = select_percents(move_why_f,1,.,questions,choices,"percent"),
    move_why_f_2_label = select_percents(move_why_f,2,.,questions,choices,"label"),
    move_why_f_2_pct = select_percents(move_why_f,2,.,questions,choices,"percent"),
    move_why_f_3_label = select_percents(move_why_f,3,.,questions,choices,"label"),
    move_why_f_3_pct = select_percents(move_why_f,3,.,questions,choices,"percent"),
    livelihood_1_label = select_percents(livelihood,1,.,questions,choices,"label"),
    livelihood_1_pct = select_percents(livelihood,1,.,questions,choices,"percent"),
    livelihood_2_label = select_percents(livelihood,2,.,questions,choices,"label"),
    livelihood_2_pct = select_percents(livelihood,2,.,questions,choices,"percent"),
    livelihood_3_label = select_percents(livelihood,3,.,questions,choices,"label"),
    livelihood_3_pct = select_percents(livelihood,3,.,questions,choices,"percent"),
    food_source_1_label = select_percents(food_source,1,.,questions,choices,"label"),
    food_source_1_pct = select_percents(food_source,1,.,questions,choices,"percent"),
    food_source_2_label = select_percents(food_source,2,.,questions,choices,"label"),
    food_source_2_pct = select_percents(food_source,2,.,questions,choices,"percent"),
    food_source_3_label = select_percents(food_source,3,.,questions,choices,"label"),
    food_source_3_pct = select_percents(food_source,3,.,questions,choices,"percent"),
    vul_index_low = percent_response(vulnerability_classification,.,"lower_risk"),
    vul_index_moderate = percent_response(vulnerability_classification,.,"moderate_risk"),
    vul_index_moderate_high = percent_response(vulnerability_classification,.,"moderate_high_risk"),
    vul_index_high = percent_response(vulnerability_classification,.,"higher_risk"),
    covid_aware_yes = percent_response(covid_aware,.,"yes"),
    covid_aware_part = percent_response(covid_aware,.,"part"),
    covid_aware_no = percent_response(covid_aware,.,"no"),
    covid_concern_yes = percent_response(covid_concern,.,"yes"),
    covid_concern_no = percent_response(covid_concern,.,"no"),
    covid_concern_dk = percent_response(covid_concern,.,"dont_know"),
    covid_info_1_label = select_percents(covid_info,1,.,questions,choices,"label"),
    covid_info_1_pct = select_percents(covid_info,1,.,questions,choices,"percent"),
    covid_info_2_label = select_percents(covid_info,2,.,questions,choices,"label"),
    covid_info_2_pct = select_percents(covid_info,2,.,questions,choices,"percent"),
    covid_info_3_label = select_percents(covid_info,3,.,questions,choices,"label"),
    covid_info_3_pct = select_percents(covid_info,3,.,questions,choices,"percent"),
    covid_safeprac_1_label = select_percents(covid_safeprac,1,.,questions,choices,"label"),
    covid_safeprac_1_pct = select_percents(covid_safeprac,1,.,questions,choices,"percent"),
    covid_safeprac_2_label = select_percents(covid_safeprac,2,.,questions,choices,"label"),
    covid_safeprac_2_pct = select_percents(covid_safeprac,2,.,questions,choices,"percent"),
    covid_safeprac_3_label = select_percents(covid_safeprac,3,.,questions,choices,"label"),
    covid_safeprac_3_pct = select_percents(covid_safeprac,3,.,questions,choices,"percent"),
    aid_govt_yes = percent_response(aid_govt,.,"yes"),
    aid_govt_no = percent_response(aid_govt,.,"no"),
    aid_govt_dk = percent_response(aid_govt,.,"dont_know"),
    aid_services_1_label = select_percents(aid_services,1,.,questions,choices,"label"),
    aid_services_1_pct = select_percents(aid_services,1,.,questions,choices,"percent"),
    aid_services_2_label = select_percents(aid_services,2,.,questions,choices,"label"),
    aid_services_2_pct = select_percents(aid_services,2,.,questions,choices,"percent"),
    aid_services_3_label = select_percents(aid_services,3,.,questions,choices,"label"),
    aid_services_3_pct = select_percents(aid_services,3,.,questions,choices,"percent"),
    vul_chronic_fs = mean(vul_chronic_fs,na.rm = T)*100,
    soap_avail_yes = percent_response(soap_avail,.,"yes"),
    soap_avail_no = percent_response(soap_avail,.,"no"),
    soap_avail_dk = percent_response(soap_avail,.,"dont_know"),
    using_public_facility = mean(using_public_facility,na.rm = T)* 100,
    handwash_crowded_yes = percent_response(handwash_crowded,.,"yes"),
    handwash_crowded_no = percent_response(handwash_crowded,.,"no"),
    handwash_crowded_dk = percent_response(handwash_crowded,.,"dont_know"),
    water_point_yes = percent_response(water_point,.,"yes"),
    water_point_no_further = percent_response(water_point,.,"no_further"),
    water_point_no_none = percent_response(water_point,.,"no_none"),
    tap_sanitize_all = percent_response(tap_sanitize,.,"all"),
    tap_sanitize_some = percent_response(tap_sanitize,.,"some"),
    tap_sanitize_no = percent_response(tap_sanitize,.,"no"),
    tap_sanitize_dk = percent_response(tap_sanitize,.,"dont_know"),
    safety_change_increase = percent_response(safety_change,.,"yes_increase"),
    safety_change_decrease = percent_response(safety_change,.,"yes_decrease"),
    safety_change_no = percent_response(safety_change,.,"no_change"),
    safety_change_dk = percent_response(safety_change,.,"dont_know"),
    covid_coping_1_label = select_percents(covid_coping,1,.,questions,choices,"label"),
    covid_coping_1_pct = select_percents(covid_coping,1,.,questions,choices,"percent"),
    covid_coping_2_label = select_percents(covid_coping,2,.,questions,choices,"label"),
    covid_coping_2_pct = select_percents(covid_coping,2,.,questions,choices,"percent"),
    covid_coping_3_label = select_percents(covid_coping,3,.,questions,choices,"label"),
    covid_coping_3_pct = select_percents(covid_coping,3,.,questions,choices,"percent"),
    mhpss_secondary_1_label = select_percents(mhpss_secondary,1,.,questions,choices,"label"),
    mhpss_secondary_1_pct = select_percents(mhpss_secondary,1,.,questions,choices,"percent"),
    mhpss_secondary_2_label = select_percents(mhpss_secondary,2,.,questions,choices,"label"),
    mhpss_secondary_2_pct = select_percents(mhpss_secondary,2,.,questions,choices,"percent"),
    mhpss_secondary_3_label = select_percents(mhpss_secondary,3,.,questions,choices,"label"),
    mhpss_secondary_3_pct = select_percents(mhpss_secondary,3,.,questions,choices,"percent"),
    vul_sleeping_prop = mean(vul_sleeping_prop,na.rm = T)*100,
    covid_shelter_1_label = select_percents(covid_shelter,1,.,questions,choices,"label"),
    covid_shelter_1_pct = select_percents(covid_shelter,1,.,questions,choices,"percent"),
    covid_shelter_2_label = select_percents(covid_shelter,2,.,questions,choices,"label"),
    covid_shelter_2_pct = select_percents(covid_shelter,2,.,questions,choices,"percent"),
    covid_shelter_3_label = select_percents(covid_shelter,3,.,questions,choices,"label"),
    covid_shelter_3_pct = select_percents(covid_shelter,3,.,questions,choices,"percent"),
    market_soldout_yes = percent_response(market_soldout,.,"yes"),
    market_soldout_no = percent_response(market_soldout,.,"no"),
    market_soldout_dk = percent_response(market_soldout,.,"dont_know"),
    soldout_item_1_label = select_percents(soldout_item,1,.,questions,choices,"label"),
    soldout_item_1_pct = select_percents(soldout_item,1,.,questions,choices,"percent"),
    soldout_item_2_label = select_percents(soldout_item,2,.,questions,choices,"label"),
    soldout_item_2_pct = select_percents(soldout_item,2,.,questions,choices,"percent"),
    soldout_item_3_label = select_percents(soldout_item,3,.,questions,choices,"label"),
    soldout_item_3_pct = select_percents(soldout_item,3,.,questions,choices,"percent"),
    work_change_fullstop = percent_response(work_change,.,"full_stop"),
    work_change_partstop = percent_response(work_change,.,"part_stop"),
    work_change_nostop = percent_response(work_change,.,"no_stop"),
    school_alternatives.other_facility = round(mean(school_alternatives.other_facility,na.rm = T)*100,2),
    school_alternatives.home_school = round(mean(school_alternatives.home_school,na.rm = T)*100,2),
    school_alternatives.other = round(mean(school_alternatives.other,na.rm = T)*100,2),
    school_alternatives.no = round(mean(school_alternatives.no,na.rm = T)*100,2),
    school_alternatives.dont_know = round(mean(school_alternatives.dont_know,na.rm = T)*100,2)
  )
 
 dm_overall %>% write_csv("./output/datamerge_overall.csv")
 
 dm_region <- parent_created %>%
   group_by(region) %>%
   summarise(
     nb_sites = n(),
     idp_hhs = sum(idp_hhs,na.rm = T),
     idp_indvl =sum(idp_indvl,na.rm = T),
     prolonged_hhs = sum(prolonged_hhs,na.rm = T),
     prolonged_indvl = sum(prolonged_indvl,na.rm = T),
     protracted_hhs = sum(protracted_hhs,na.rm = T),
     protracted_indvl = sum(protracted_indvl, na.rm = T),
     refugee_hhs = sum(refugee_hhs,na.rm = T),
     refugee_indvl = sum(refugee_indvl,na.rm = T),
     returnee_hhs = sum(returnee_hhs,na.rm = T),
     returnee_indvl = sum(returnee_indvl,na.rm = T),
     economic_hhs = sum(economic_hhs,na.rm = T),
     economic_indvl = sum(economic_indvl, na.rm = T),
     nomad_hhs = sum(nomad_hhs, na.rm = T),
     nomad_indvl = sum(nomad_indvl, na.rm = T),
     host_hhs = sum(host_hhs, na.rm = T),
     host_indvl = sum(host_indvl, na.rm = T),
     iset_population_discrete = percent_response(iset_population,.,"discrete"),
     iset_population_mixed = percent_response(iset_population,.,"mixed"),
     location_urban = percent_response(location_fs,.,"urban"),
     location_suburban = percent_response(location_fs,.,"suburban"),
     location_rural = percent_response(location_fs,.,"rural"),
     idp_mixed = round(mean(idp_mixed,na.rm = T)*100,2),
     idp_discrete = round(mean(idp_discrete,na.rm = T)*100,2),
     prolong_mixed = round(mean(prolong_mixed,na.rm = T)*100,2),
     prolong_discrete= round(mean(prolong_discrete,na.rm = T)*100,2),
     protract_mixed=round(mean(protract_mixed,na.rm = T)*100,2),
     protract_discrete=mean(protract_discrete,na.rm = T)*100,
     refugee_mixed= round(mean(refugee_mixed,na.rm = T)*100,2),
     refugee_discrete=mean(refugee_discrete,na.rm = T)*100,
     returnee_mixed=round(mean(returnee_mixed,na.rm = T)*100,2),
     returnee_discrete=round(mean(returnee_discrete,na.rm = T)*100,2),
     economic_mixed=round(mean(economic_mixed,na.rm = T)*100,2),
     economic_discrete=round(mean(economic_discrete,na.rm = T)*100,2),
     nomad_mixed=round(mean(nomad_mixed,na.rm = T)*100,2),
     nomad_discrete=round(mean(nomad_discrete,na.rm = T)*100,2),
     migrant_population.idp = round(mean(migrant_population.idp,na.rm = T)*100,2),
     migrant_population.prolong = round(mean(migrant_population.prolong,na.rm = T)*100,2),
     migrant_population.protract = round(mean(migrant_population.protract,na.rm = T)*100,2),
     migrant_population.refugee = round(mean(migrant_population.refugee,na.rm = T)*100,2),
     migrant_population.returnee = round(mean(migrant_population.returnee,na.rm = T)*100,2),
     relocate_plan_yes = percent_response(relocate_plan,.,"yes"),
     relocate_plan_no = percent_response(relocate_plan,.,"no"),
     relocate_plan_dk = percent_response(relocate_plan,.,"dont_know"),
     relocate_pushpull_1_label = select_percents(relocate_pushpull,1,.,questions,choices,"label"),
     relocate_pushpull_1_pct = select_percents(relocate_pushpull,1,.,questions,choices,"percent"),
     relocate_pushpull_2_label = select_percents(relocate_pushpull,2,.,questions,choices,"label"),
     relocate_pushpull_2_pct = select_percents(relocate_pushpull,2,.,questions,choices,"percent"),
     relocate_pushpull_3_label = select_percents(relocate_pushpull,3,.,questions,choices,"label"),
     relocate_pushpull_3_pct = select_percents(relocate_pushpull,3,.,questions,choices,"percent"),
     five_years_yes = percent_response(five_years,.,"yes"),
     five_years_no = percent_response(five_years,.,"no"),
     five_years_dk = percent_response(five_years,.,"dont_know"),
     idp_3mo_hhs = sum(idp_3mo_hhs,na.rm = T),
     idp_prov_origin_1_label = select_percents(idp_prov_origin,1,.,questions,choices,"label"),
     idp_prov_origin_1_pct = select_percents(idp_prov_origin,1,.,questions,choices,"percent"),
     idp_prov_origin_2_label = select_percents(idp_prov_origin,2,.,questions,choices,"label"),
     idp_prov_origin_2_pct = select_percents(idp_prov_origin,2,.,questions,choices,"percent"),
     idp_prov_origin_3_label = select_percents(idp_prov_origin,3,.,questions,choices,"label"),
     idp_prov_origin_3_pct = select_percents(idp_prov_origin,3,.,questions,choices,"percent"),
     returnee_3mo_hhs = sum(returnee_3mo_hhs,na.rm = T),
     returnee_origin_1_label = select_percents(returnee_origin,1,.,questions,choices,"label"),
     returnee_origin_1_pct = select_percents(returnee_origin,1,.,questions,choices,"percent"),
     returnee_origin_2_label = select_percents(returnee_origin,2,.,questions,choices,"label"),
     returnee_origin_2_pct = select_percents(returnee_origin,2,.,questions,choices,"percent"),
     returnee_origin_3_label = select_percents(returnee_origin,3,.,questions,choices,"label"),
     returnee_origin_3_pct = select_percents(returnee_origin,3,.,questions,choices,"percent"),
     shelter_type_1_label = select_percents(shelter_type,1,.,questions,choices,"label"),
     shelter_type_1_pct = select_percents(shelter_type,1,.,questions,choices,"percent"),
     shelter_type_2_label = select_percents(shelter_type,2,.,questions,choices,"label"),
     shelter_type_2_pct = select_percents(shelter_type,2,.,questions,choices,"percent"),
     shelter_type_3_label = select_percents(shelter_type,3,.,questions,choices,"label"),
     shelter_type_3_pct = select_percents(shelter_type,3,.,questions,choices,"percent"),
     tenure_insecure = percent_response(tenure_insecure,.,"yes"),
     hh_rooms = mean(hh_rooms,na.rm = T),
     accom_1_label = select_percents(accom,1,.,questions,choices,"label"),
     accom_1_pct = select_percents(accom,1,.,questions,choices,"percent"),
     accom_2_label = select_percents(accom,2,.,questions,choices,"label"),
     accom_2_pct = select_percents(accom,2,.,questions,choices,"percent"),
     accom_3_label = select_percents(accom,3,.,questions,choices,"label"),
     accom_3_pct = select_percents(accom,3,.,questions,choices,"percent"),
     host_relation_positive = percent_response(host_relation,.,"positive"),
     host_relation_neutral = percent_response(host_relation,.,"neutral"),
     host_relation_negative = percent_response(host_relation,.,"negative"),
     host_relation_prefer_not = percent_response(host_relation,.,"prefer_not"),
     eviction_threat_yes = percent_response(eviction_threat,.,"yes"),
     eviction_threat_no = percent_response(eviction_threat,.,"no"),
     eviction_threat_dk = percent_response(eviction_threat,.,"dont_know"),
     eviction_threat_local_auth = round(mean(eviction_threat_why.local_auth,na.rm = T)*100,2),
     eviction_threat_gvt = round(mean(eviction_threat_why.government,na.rm = T)*100,2),
     eviction_threat_local_host_comm = round(mean(eviction_threat_why.host_comm,na.rm = T)*100,2),
     eviction_threat_local_ot = round(mean(eviction_threat_why.other,na.rm = T)*100,2),
     comm_represent_yes = percent_response(comm_represent,.,"yes"),
     comm_represent_no = percent_response(comm_represent,.,"no"),
     comm_represent_dk = percent_response(comm_represent,.,"dont_know"),
     relocation_yes = percent_response(relocation,.,"yes"),
     relocation_no = percent_response(relocation,.,"no"),
     site_land_yes = percent_response(site_land,.,"yes"),
     site_land_no = percent_response(site_land,.,"no"),
     site_land_dk = percent_response(site_land,.,"dont_know"),
     site_land_owner_gvt = percent_response(site_land_owner,.,"government"),
     site_land_owner_prv = percent_response(site_land_owner,.,"private"),
     site_land_owner_un = percent_response(site_land_owner,.,"un"),
     site_land_owner_common = percent_response(site_land_owner,.,"common"),
     site_land_owner_ot = percent_response(site_land_owner,.,"other"),
     water_distance_fs = percent_response(water_distance_fs,.,"yes"),
     water_source_fs = mean(water_source_fs,na.rm = T),
     water_barrier_1_label = select_percents(water_barrier,1,.,questions,choices,"label"),
     water_barrier_1_pct = select_percents(water_barrier,1,.,questions,choices,"percent"),
     water_barrier_2_label = select_percents(water_barrier,2,.,questions,choices,"label"),
     water_barrier_2_pct = select_percents(water_barrier,2,.,questions,choices,"percent"),
     water_barrier_3_label = select_percents(water_barrier,3,.,questions,choices,"label"),
     water_barrier_3_pct = select_percents(water_barrier,3,.,questions,choices,"percent"),
     health_distance_fs = percent_response(health_distance_fs,.,"yes"),
     health_satisfy_constraint_yes = percent_response(health_satisfy_constraint,.,"yes"),
     health_satisfy_constraint_no = percent_response(health_satisfy_constraint,.,"no"),
     health_satisfy_constraint_dk = percent_response(health_satisfy_constraint,.,"dont_know"),
     health_unsatisfy_constraint.crowded = round(mean(health_unsatisfy_constraint.crowded,na.rm = T)*100,2),
     health_unsatisfy_constraint.hours = round(mean(health_unsatisfy_constraint.hours,na.rm = T)*100,2),
     health_unsatisfy_constraint.expensive = round(mean(health_unsatisfy_constraint.expensive,na.rm = T)*100,2),
     health_unsatisfy_constraint.drug_unavail = round(mean(health_unsatisfy_constraint.drug_unavail,na.rm = T)*100,2),
     health_unsatisfy_constraint.staff_behave = round(mean(health_unsatisfy_constraint.staff_behave,na.rm = T)*100,2),
     health_unsatisfy_constraint.other = round(mean(health_unsatisfy_constraint.other,na.rm = T)*100,2),
     health_unsatisfy_constraint.dont_know = round(mean(health_unsatisfy_constraint.dont_know,na.rm = T)*100,2),
     mhpss_aware_yes = percent_response(mhpss_aware,.,"yes"),
     mhpss_aware_no = percent_response(mhpss_aware,.,"no"),
     mhpss_aware_dk = percent_response(mhpss_aware,.,"dont_know"),
     health_barrier_1_label = select_percents(health_barrier,1,.,questions,choices,"label"),
     health_barrier_1_pct = select_percents(health_barrier,1,.,questions,choices,"percent"),
     health_barrier_2_label = select_percents(health_barrier,2,.,questions,choices,"label"),
     health_barrier_2_pct = select_percents(health_barrier,2,.,questions,choices,"percent"),
     health_barrier_3_label = select_percents(health_barrier,3,.,questions,choices,"label"),
     health_barrier_3_pct = select_percents(health_barrier,3,.,questions,choices,"percent"),
     safe_likert_verygood = percent_response(safe_likert,.,"very_good"),
     safe_likert_good = percent_response(safe_likert,.,"good"),
     safe_likert_neutral = percent_response(safe_likert,.,"neutral"),
     safe_likert_poor = percent_response(safe_likert,.,"poor_qual"),
     safe_likert_verypoor = percent_response(safe_likert,.,"very_poor"),
     move_free_m_yes = percent_response(move_free_m,.,"yes"),
     move_free_m_no = percent_response(move_free_m,.,"no"),
     move_free_m_dk = percent_response(move_free_m,.,"dont_know"),
     move_why_m_1_label = select_percents(move_why_m,1,.,questions,choices,"label"),
     move_why_m_1_pct = select_percents(move_why_m,1,.,questions,choices,"percent"),
     move_why_m_2_label = select_percents(move_why_m,2,.,questions,choices,"label"),
     move_why_m_2_pct = select_percents(move_why_m,2,.,questions,choices,"percent"),
     move_why_m_3_label = select_percents(move_why_m,3,.,questions,choices,"label"),
     move_why_m_3_pct = select_percents(move_why_m,3,.,questions,choices,"percent"),
     move_free_f_yes = percent_response(move_free_f,.,"yes"),
     move_free_f_no = percent_response(move_free_f,.,"no"),
     move_free_f_dk = percent_response(move_free_f,.,"dont_know"),
     move_why_f_1_label = select_percents(move_why_f,1,.,questions,choices,"label"),
     move_why_f_1_pct = select_percents(move_why_f,1,.,questions,choices,"percent"),
     move_why_f_2_label = select_percents(move_why_f,2,.,questions,choices,"label"),
     move_why_f_2_pct = select_percents(move_why_f,2,.,questions,choices,"percent"),
     move_why_f_3_label = select_percents(move_why_f,3,.,questions,choices,"label"),
     move_why_f_3_pct = select_percents(move_why_f,3,.,questions,choices,"percent"),
     livelihood_1_label = select_percents(livelihood,1,.,questions,choices,"label"),
     livelihood_1_pct = select_percents(livelihood,1,.,questions,choices,"percent"),
     livelihood_2_label = select_percents(livelihood,2,.,questions,choices,"label"),
     livelihood_2_pct = select_percents(livelihood,2,.,questions,choices,"percent"),
     livelihood_3_label = select_percents(livelihood,3,.,questions,choices,"label"),
     livelihood_3_pct = select_percents(livelihood,3,.,questions,choices,"percent"),
     food_source_1_label = select_percents(food_source,1,.,questions,choices,"label"),
     food_source_1_pct = select_percents(food_source,1,.,questions,choices,"percent"),
     food_source_2_label = select_percents(food_source,2,.,questions,choices,"label"),
     food_source_2_pct = select_percents(food_source,2,.,questions,choices,"percent"),
     food_source_3_label = select_percents(food_source,3,.,questions,choices,"label"),
     food_source_3_pct = select_percents(food_source,3,.,questions,choices,"percent"),
     vul_index_low = percent_response(vulnerability_classification,.,"lower_risk"),
     vul_index_moderate = percent_response(vulnerability_classification,.,"moderate_risk"),
     vul_index_moderate_high = percent_response(vulnerability_classification,.,"moderate_high_risk"),
     vul_index_high = percent_response(vulnerability_classification,.,"higher_risk"),
     covid_aware_yes = percent_response(covid_aware,.,"yes"),
     covid_aware_part = percent_response(covid_aware,.,"part"),
     covid_aware_no = percent_response(covid_aware,.,"no"),
     covid_concern_yes = percent_response(covid_concern,.,"yes"),
     covid_concern_no = percent_response(covid_concern,.,"no"),
     covid_concern_dk = percent_response(covid_concern,.,"dont_know"),
     covid_info_1_label = select_percents(covid_info,1,.,questions,choices,"label"),
     covid_info_1_pct = select_percents(covid_info,1,.,questions,choices,"percent"),
     covid_info_2_label = select_percents(covid_info,2,.,questions,choices,"label"),
     covid_info_2_pct = select_percents(covid_info,2,.,questions,choices,"percent"),
     covid_info_3_label = select_percents(covid_info,3,.,questions,choices,"label"),
     covid_info_3_pct = select_percents(covid_info,3,.,questions,choices,"percent"),
     covid_safeprac_1_label = select_percents(covid_safeprac,1,.,questions,choices,"label"),
     covid_safeprac_1_pct = select_percents(covid_safeprac,1,.,questions,choices,"percent"),
     covid_safeprac_2_label = select_percents(covid_safeprac,2,.,questions,choices,"label"),
     covid_safeprac_2_pct = select_percents(covid_safeprac,2,.,questions,choices,"percent"),
     covid_safeprac_3_label = select_percents(covid_safeprac,3,.,questions,choices,"label"),
     covid_safeprac_3_pct = select_percents(covid_safeprac,3,.,questions,choices,"percent"),
     aid_govt_yes = percent_response(aid_govt,.,"yes"),
     aid_govt_no = percent_response(aid_govt,.,"no"),
     aid_govt_dk = percent_response(aid_govt,.,"dont_know"),
     aid_services_1_label = select_percents(aid_services,1,.,questions,choices,"label"),
     aid_services_1_pct = select_percents(aid_services,1,.,questions,choices,"percent"),
     aid_services_2_label = select_percents(aid_services,2,.,questions,choices,"label"),
     aid_services_2_pct = select_percents(aid_services,2,.,questions,choices,"percent"),
     aid_services_3_label = select_percents(aid_services,3,.,questions,choices,"label"),
     aid_services_3_pct = select_percents(aid_services,3,.,questions,choices,"percent"),
     vul_chronic_fs = mean(vul_chronic_fs,na.rm = T)*100,
     soap_avail_yes = percent_response(soap_avail,.,"yes"),
     soap_avail_no = percent_response(soap_avail,.,"no"),
     soap_avail_dk = percent_response(soap_avail,.,"dont_know"),
     using_public_facility = mean(using_public_facility,na.rm = T)* 100,
     handwash_crowded_yes = percent_response(handwash_crowded,.,"yes"),
     handwash_crowded_no = percent_response(handwash_crowded,.,"no"),
     handwash_crowded_dk = percent_response(handwash_crowded,.,"dont_know"),
     water_point_yes = percent_response(water_point,.,"yes"),
     water_point_no_further = percent_response(water_point,.,"no_further"),
     water_point_no_none = percent_response(water_point,.,"no_none"),
     tap_sanitize_all = percent_response(tap_sanitize,.,"all"),
     tap_sanitize_some = percent_response(tap_sanitize,.,"some"),
     tap_sanitize_no = percent_response(tap_sanitize,.,"no"),
     tap_sanitize_dk = percent_response(tap_sanitize,.,"dont_know"),
     safety_change_increase = percent_response(safety_change,.,"yes_increase"),
     safety_change_decrease = percent_response(safety_change,.,"yes_decrease"),
     safety_change_no = percent_response(safety_change,.,"no_change"),
     safety_change_dk = percent_response(safety_change,.,"dont_know"),
     covid_coping_1_label = select_percents(covid_coping,1,.,questions,choices,"label"),
     covid_coping_1_pct = select_percents(covid_coping,1,.,questions,choices,"percent"),
     covid_coping_2_label = select_percents(covid_coping,2,.,questions,choices,"label"),
     covid_coping_2_pct = select_percents(covid_coping,2,.,questions,choices,"percent"),
     covid_coping_3_label = select_percents(covid_coping,3,.,questions,choices,"label"),
     covid_coping_3_pct = select_percents(covid_coping,3,.,questions,choices,"percent"),
     mhpss_secondary_1_label = select_percents(mhpss_secondary,1,.,questions,choices,"label"),
     mhpss_secondary_1_pct = select_percents(mhpss_secondary,1,.,questions,choices,"percent"),
     mhpss_secondary_2_label = select_percents(mhpss_secondary,2,.,questions,choices,"label"),
     mhpss_secondary_2_pct = select_percents(mhpss_secondary,2,.,questions,choices,"percent"),
     mhpss_secondary_3_label = select_percents(mhpss_secondary,3,.,questions,choices,"label"),
     mhpss_secondary_3_pct = select_percents(mhpss_secondary,3,.,questions,choices,"percent"),
     vul_sleeping_prop = mean(vul_sleeping_prop,na.rm = T)*100,
     covid_shelter_1_label = select_percents(covid_shelter,1,.,questions,choices,"label"),
     covid_shelter_1_pct = select_percents(covid_shelter,1,.,questions,choices,"percent"),
     covid_shelter_2_label = select_percents(covid_shelter,2,.,questions,choices,"label"),
     covid_shelter_2_pct = select_percents(covid_shelter,2,.,questions,choices,"percent"),
     covid_shelter_3_label = select_percents(covid_shelter,3,.,questions,choices,"label"),
     covid_shelter_3_pct = select_percents(covid_shelter,3,.,questions,choices,"percent"),
     market_soldout_yes = percent_response(market_soldout,.,"yes"),
     market_soldout_no = percent_response(market_soldout,.,"no"),
     market_soldout_dk = percent_response(market_soldout,.,"dont_know"),
     soldout_item_1_label = select_percents(soldout_item,1,.,questions,choices,"label"),
     soldout_item_1_pct = select_percents(soldout_item,1,.,questions,choices,"percent"),
     soldout_item_2_label = select_percents(soldout_item,2,.,questions,choices,"label"),
     soldout_item_2_pct = select_percents(soldout_item,2,.,questions,choices,"percent"),
     soldout_item_3_label = select_percents(soldout_item,3,.,questions,choices,"label"),
     soldout_item_3_pct = select_percents(soldout_item,3,.,questions,choices,"percent"),
     work_change_fullstop = percent_response(work_change,.,"full_stop"),
     work_change_partstop = percent_response(work_change,.,"part_stop"),
     work_change_nostop = percent_response(work_change,.,"no_stop"),
     school_alternatives.other_facility = round(mean(school_alternatives.other_facility,na.rm = T)*100,2),
     school_alternatives.home_school = round(mean(school_alternatives.home_school,na.rm = T)*100,2),
     school_alternatives.other = round(mean(school_alternatives.other,na.rm = T)*100,2),
     school_alternatives.no = round(mean(school_alternatives.no,na.rm = T)*100,2),
     school_alternatives.dont_know = round(mean(school_alternatives.dont_know,na.rm = T)*100,2)
   )
dm_region %>% write_csv("./output/datamerge_region.csv")

dm_province <- parent_created %>%
  group_by(province) %>%
  summarise(
    nb_sites = n(),
    idp_hhs = sum(idp_hhs,na.rm = T),
    idp_indvl =sum(idp_indvl,na.rm = T),
    prolonged_hhs = sum(prolonged_hhs,na.rm = T),
    prolonged_indvl = sum(prolonged_indvl,na.rm = T),
    protracted_hhs = sum(protracted_hhs,na.rm = T),
    protracted_indvl = sum(protracted_indvl, na.rm = T),
    refugee_hhs = sum(refugee_hhs,na.rm = T),
    refugee_indvl = sum(refugee_indvl,na.rm = T),
    returnee_hhs = sum(returnee_hhs,na.rm = T),
    returnee_indvl = sum(returnee_indvl,na.rm = T),
    economic_hhs = sum(economic_hhs,na.rm = T),
    economic_indvl = sum(economic_indvl, na.rm = T),
    nomad_hhs = sum(nomad_hhs, na.rm = T),
    nomad_indvl = sum(nomad_indvl, na.rm = T),
    host_hhs = sum(host_hhs, na.rm = T),
    host_indvl = sum(host_indvl, na.rm = T),
    iset_population_discrete = percent_response(iset_population,.,"discrete"),
    iset_population_mixed = percent_response(iset_population,.,"mixed"),
    location_urban = percent_response(location_fs,.,"urban"),
    location_suburban = percent_response(location_fs,.,"suburban"),
    location_rural = percent_response(location_fs,.,"rural"),
    idp_mixed = round(mean(idp_mixed,na.rm = T)*100,2),
    idp_discrete = round(mean(idp_discrete,na.rm = T)*100,2),
    prolong_mixed = round(mean(prolong_mixed,na.rm = T)*100,2),
    prolong_discrete= round(mean(prolong_discrete,na.rm = T)*100,2),
    protract_mixed=round(mean(protract_mixed,na.rm = T)*100,2),
    protract_discrete=mean(protract_discrete,na.rm = T)*100,
    refugee_mixed= round(mean(refugee_mixed,na.rm = T)*100,2),
    refugee_discrete=mean(refugee_discrete,na.rm = T)*100,
    returnee_mixed=round(mean(returnee_mixed,na.rm = T)*100,2),
    returnee_discrete=round(mean(returnee_discrete,na.rm = T)*100,2),
    economic_mixed=round(mean(economic_mixed,na.rm = T)*100,2),
    economic_discrete=round(mean(economic_discrete,na.rm = T)*100,2),
    nomad_mixed=round(mean(nomad_mixed,na.rm = T)*100,2),
    nomad_discrete=round(mean(nomad_discrete,na.rm = T)*100,2),
    migrant_population.idp = round(mean(migrant_population.idp,na.rm = T)*100,2),
    migrant_population.prolong = round(mean(migrant_population.prolong,na.rm = T)*100,2),
    migrant_population.protract = round(mean(migrant_population.protract,na.rm = T)*100,2),
    migrant_population.refugee = round(mean(migrant_population.refugee,na.rm = T)*100,2),
    migrant_population.returnee = round(mean(migrant_population.returnee,na.rm = T)*100,2),
    relocate_plan_yes = percent_response(relocate_plan,.,"yes"),
    relocate_plan_no = percent_response(relocate_plan,.,"no"),
    relocate_plan_dk = percent_response(relocate_plan,.,"dont_know"),
    relocate_pushpull_1_label = select_percents(relocate_pushpull,1,.,questions,choices,"label"),
    relocate_pushpull_1_pct = select_percents(relocate_pushpull,1,.,questions,choices,"percent"),
    relocate_pushpull_2_label = select_percents(relocate_pushpull,2,.,questions,choices,"label"),
    relocate_pushpull_2_pct = select_percents(relocate_pushpull,2,.,questions,choices,"percent"),
    relocate_pushpull_3_label = select_percents(relocate_pushpull,3,.,questions,choices,"label"),
    relocate_pushpull_3_pct = select_percents(relocate_pushpull,3,.,questions,choices,"percent"),
    five_years_yes = percent_response(five_years,.,"yes"),
    five_years_no = percent_response(five_years,.,"no"),
    five_years_dk = percent_response(five_years,.,"dont_know"),
    idp_3mo_hhs = sum(idp_3mo_hhs,na.rm = T),
    idp_prov_origin_1_label = select_percents(idp_prov_origin,1,.,questions,choices,"label"),
    idp_prov_origin_1_pct = select_percents(idp_prov_origin,1,.,questions,choices,"percent"),
    idp_prov_origin_2_label = select_percents(idp_prov_origin,2,.,questions,choices,"label"),
    idp_prov_origin_2_pct = select_percents(idp_prov_origin,2,.,questions,choices,"percent"),
    idp_prov_origin_3_label = select_percents(idp_prov_origin,3,.,questions,choices,"label"),
    idp_prov_origin_3_pct = select_percents(idp_prov_origin,3,.,questions,choices,"percent"),
    returnee_3mo_hhs = sum(returnee_3mo_hhs,na.rm = T),
    returnee_origin_1_label = select_percents(returnee_origin,1,.,questions,choices,"label"),
    returnee_origin_1_pct = select_percents(returnee_origin,1,.,questions,choices,"percent"),
    returnee_origin_2_label = select_percents(returnee_origin,2,.,questions,choices,"label"),
    returnee_origin_2_pct = select_percents(returnee_origin,2,.,questions,choices,"percent"),
    returnee_origin_3_label = select_percents(returnee_origin,3,.,questions,choices,"label"),
    returnee_origin_3_pct = select_percents(returnee_origin,3,.,questions,choices,"percent"),
    shelter_type_1_label = select_percents(shelter_type,1,.,questions,choices,"label"),
    shelter_type_1_pct = select_percents(shelter_type,1,.,questions,choices,"percent"),
    shelter_type_2_label = select_percents(shelter_type,2,.,questions,choices,"label"),
    shelter_type_2_pct = select_percents(shelter_type,2,.,questions,choices,"percent"),
    shelter_type_3_label = select_percents(shelter_type,3,.,questions,choices,"label"),
    shelter_type_3_pct = select_percents(shelter_type,3,.,questions,choices,"percent"),
    tenure_insecure = percent_response(tenure_insecure,.,"yes"),
    hh_rooms = mean(hh_rooms,na.rm = T),
    accom_1_label = select_percents(accom,1,.,questions,choices,"label"),
    accom_1_pct = select_percents(accom,1,.,questions,choices,"percent"),
    accom_2_label = select_percents(accom,2,.,questions,choices,"label"),
    accom_2_pct = select_percents(accom,2,.,questions,choices,"percent"),
    accom_3_label = select_percents(accom,3,.,questions,choices,"label"),
    accom_3_pct = select_percents(accom,3,.,questions,choices,"percent"),
    host_relation_positive = percent_response(host_relation,.,"positive"),
    host_relation_neutral = percent_response(host_relation,.,"neutral"),
    host_relation_negative = percent_response(host_relation,.,"negative"),
    host_relation_prefer_not = percent_response(host_relation,.,"prefer_not"),
    eviction_threat_yes = percent_response(eviction_threat,.,"yes"),
    eviction_threat_no = percent_response(eviction_threat,.,"no"),
    eviction_threat_dk = percent_response(eviction_threat,.,"dont_know"),
    eviction_threat_local_auth = round(mean(eviction_threat_why.local_auth,na.rm = T)*100,2),
    eviction_threat_gvt = round(mean(eviction_threat_why.government,na.rm = T)*100,2),
    eviction_threat_local_host_comm = round(mean(eviction_threat_why.host_comm,na.rm = T)*100,2),
    eviction_threat_local_ot = round(mean(eviction_threat_why.other,na.rm = T)*100,2),
    comm_represent_yes = percent_response(comm_represent,.,"yes"),
    comm_represent_no = percent_response(comm_represent,.,"no"),
    comm_represent_dk = percent_response(comm_represent,.,"dont_know"),
    relocation_yes = percent_response(relocation,.,"yes"),
    relocation_no = percent_response(relocation,.,"no"),
    site_land_yes = percent_response(site_land,.,"yes"),
    site_land_no = percent_response(site_land,.,"no"),
    site_land_dk = percent_response(site_land,.,"dont_know"),
    site_land_owner_gvt = percent_response(site_land_owner,.,"government"),
    site_land_owner_prv = percent_response(site_land_owner,.,"private"),
    site_land_owner_un = percent_response(site_land_owner,.,"un"),
    site_land_owner_common = percent_response(site_land_owner,.,"common"),
    site_land_owner_ot = percent_response(site_land_owner,.,"other"),
    water_distance_fs = percent_response(water_distance_fs,.,"yes"),
    water_source_fs = mean(water_source_fs,na.rm = T),
    water_barrier_1_label = select_percents(water_barrier,1,.,questions,choices,"label"),
    water_barrier_1_pct = select_percents(water_barrier,1,.,questions,choices,"percent"),
    water_barrier_2_label = select_percents(water_barrier,2,.,questions,choices,"label"),
    water_barrier_2_pct = select_percents(water_barrier,2,.,questions,choices,"percent"),
    water_barrier_3_label = select_percents(water_barrier,3,.,questions,choices,"label"),
    water_barrier_3_pct = select_percents(water_barrier,3,.,questions,choices,"percent"),
    health_distance_fs = percent_response(health_distance_fs,.,"yes"),
    health_satisfy_constraint_yes = percent_response(health_satisfy_constraint,.,"yes"),
    health_satisfy_constraint_no = percent_response(health_satisfy_constraint,.,"no"),
    health_satisfy_constraint_dk = percent_response(health_satisfy_constraint,.,"dont_know"),
    health_unsatisfy_constraint.crowded = round(mean(health_unsatisfy_constraint.crowded,na.rm = T)*100,2),
    health_unsatisfy_constraint.hours = round(mean(health_unsatisfy_constraint.hours,na.rm = T)*100,2),
    health_unsatisfy_constraint.expensive = round(mean(health_unsatisfy_constraint.expensive,na.rm = T)*100,2),
    health_unsatisfy_constraint.drug_unavail = round(mean(health_unsatisfy_constraint.drug_unavail,na.rm = T)*100,2),
    health_unsatisfy_constraint.staff_behave = round(mean(health_unsatisfy_constraint.staff_behave,na.rm = T)*100,2),
    health_unsatisfy_constraint.other = round(mean(health_unsatisfy_constraint.other,na.rm = T)*100,2),
    health_unsatisfy_constraint.dont_know = round(mean(health_unsatisfy_constraint.dont_know,na.rm = T)*100,2),
    mhpss_aware_yes = percent_response(mhpss_aware,.,"yes"),
    mhpss_aware_no = percent_response(mhpss_aware,.,"no"),
    mhpss_aware_dk = percent_response(mhpss_aware,.,"dont_know"),
    health_barrier_1_label = select_percents(health_barrier,1,.,questions,choices,"label"),
    health_barrier_1_pct = select_percents(health_barrier,1,.,questions,choices,"percent"),
    health_barrier_2_label = select_percents(health_barrier,2,.,questions,choices,"label"),
    health_barrier_2_pct = select_percents(health_barrier,2,.,questions,choices,"percent"),
    health_barrier_3_label = select_percents(health_barrier,3,.,questions,choices,"label"),
    health_barrier_3_pct = select_percents(health_barrier,3,.,questions,choices,"percent"),
    safe_likert_verygood = percent_response(safe_likert,.,"very_good"),
    safe_likert_good = percent_response(safe_likert,.,"good"),
    safe_likert_neutral = percent_response(safe_likert,.,"neutral"),
    safe_likert_poor = percent_response(safe_likert,.,"poor_qual"),
    safe_likert_verypoor = percent_response(safe_likert,.,"very_poor"),
    move_free_m_yes = percent_response(move_free_m,.,"yes"),
    move_free_m_no = percent_response(move_free_m,.,"no"),
    move_free_m_dk = percent_response(move_free_m,.,"dont_know"),
    move_why_m_1_label = select_percents(move_why_m,1,.,questions,choices,"label"),
    move_why_m_1_pct = select_percents(move_why_m,1,.,questions,choices,"percent"),
    move_why_m_2_label = select_percents(move_why_m,2,.,questions,choices,"label"),
    move_why_m_2_pct = select_percents(move_why_m,2,.,questions,choices,"percent"),
    move_why_m_3_label = select_percents(move_why_m,3,.,questions,choices,"label"),
    move_why_m_3_pct = select_percents(move_why_m,3,.,questions,choices,"percent"),
    move_free_f_yes = percent_response(move_free_f,.,"yes"),
    move_free_f_no = percent_response(move_free_f,.,"no"),
    move_free_f_dk = percent_response(move_free_f,.,"dont_know"),
    move_why_f_1_label = select_percents(move_why_f,1,.,questions,choices,"label"),
    move_why_f_1_pct = select_percents(move_why_f,1,.,questions,choices,"percent"),
    move_why_f_2_label = select_percents(move_why_f,2,.,questions,choices,"label"),
    move_why_f_2_pct = select_percents(move_why_f,2,.,questions,choices,"percent"),
    move_why_f_3_label = select_percents(move_why_f,3,.,questions,choices,"label"),
    move_why_f_3_pct = select_percents(move_why_f,3,.,questions,choices,"percent"),
    livelihood_1_label = select_percents(livelihood,1,.,questions,choices,"label"),
    livelihood_1_pct = select_percents(livelihood,1,.,questions,choices,"percent"),
    livelihood_2_label = select_percents(livelihood,2,.,questions,choices,"label"),
    livelihood_2_pct = select_percents(livelihood,2,.,questions,choices,"percent"),
    livelihood_3_label = select_percents(livelihood,3,.,questions,choices,"label"),
    livelihood_3_pct = select_percents(livelihood,3,.,questions,choices,"percent"),
    food_source_1_label = select_percents(food_source,1,.,questions,choices,"label"),
    food_source_1_pct = select_percents(food_source,1,.,questions,choices,"percent"),
    food_source_2_label = select_percents(food_source,2,.,questions,choices,"label"),
    food_source_2_pct = select_percents(food_source,2,.,questions,choices,"percent"),
    food_source_3_label = select_percents(food_source,3,.,questions,choices,"label"),
    food_source_3_pct = select_percents(food_source,3,.,questions,choices,"percent"),
    vul_index_low = percent_response(vulnerability_classification,.,"lower_risk"),
    vul_index_moderate = percent_response(vulnerability_classification,.,"moderate_risk"),
    vul_index_moderate_high = percent_response(vulnerability_classification,.,"moderate_high_risk"),
    vul_index_high = percent_response(vulnerability_classification,.,"higher_risk"),
    covid_aware_yes = percent_response(covid_aware,.,"yes"),
    covid_aware_part = percent_response(covid_aware,.,"part"),
    covid_aware_no = percent_response(covid_aware,.,"no"),
    covid_concern_yes = percent_response(covid_concern,.,"yes"),
    covid_concern_no = percent_response(covid_concern,.,"no"),
    covid_concern_dk = percent_response(covid_concern,.,"dont_know"),
    covid_info_1_label = select_percents(covid_info,1,.,questions,choices,"label"),
    covid_info_1_pct = select_percents(covid_info,1,.,questions,choices,"percent"),
    covid_info_2_label = select_percents(covid_info,2,.,questions,choices,"label"),
    covid_info_2_pct = select_percents(covid_info,2,.,questions,choices,"percent"),
    covid_info_3_label = select_percents(covid_info,3,.,questions,choices,"label"),
    covid_info_3_pct = select_percents(covid_info,3,.,questions,choices,"percent"),
    covid_safeprac_1_label = select_percents(covid_safeprac,1,.,questions,choices,"label"),
    covid_safeprac_1_pct = select_percents(covid_safeprac,1,.,questions,choices,"percent"),
    covid_safeprac_2_label = select_percents(covid_safeprac,2,.,questions,choices,"label"),
    covid_safeprac_2_pct = select_percents(covid_safeprac,2,.,questions,choices,"percent"),
    covid_safeprac_3_label = select_percents(covid_safeprac,3,.,questions,choices,"label"),
    covid_safeprac_3_pct = select_percents(covid_safeprac,3,.,questions,choices,"percent"),
    aid_govt_yes = percent_response(aid_govt,.,"yes"),
    aid_govt_no = percent_response(aid_govt,.,"no"),
    aid_govt_dk = percent_response(aid_govt,.,"dont_know"),
    aid_services_1_label = select_percents(aid_services,1,.,questions,choices,"label"),
    aid_services_1_pct = select_percents(aid_services,1,.,questions,choices,"percent"),
    aid_services_2_label = select_percents(aid_services,2,.,questions,choices,"label"),
    aid_services_2_pct = select_percents(aid_services,2,.,questions,choices,"percent"),
    aid_services_3_label = select_percents(aid_services,3,.,questions,choices,"label"),
    aid_services_3_pct = select_percents(aid_services,3,.,questions,choices,"percent"),
    vul_chronic_fs = mean(vul_chronic_fs,na.rm = T)*100,
    soap_avail_yes = percent_response(soap_avail,.,"yes"),
    soap_avail_no = percent_response(soap_avail,.,"no"),
    soap_avail_dk = percent_response(soap_avail,.,"dont_know"),
    using_public_facility = mean(using_public_facility,na.rm = T)* 100,
    handwash_crowded_yes = percent_response(handwash_crowded,.,"yes"),
    handwash_crowded_no = percent_response(handwash_crowded,.,"no"),
    handwash_crowded_dk = percent_response(handwash_crowded,.,"dont_know"),
    water_point_yes = percent_response(water_point,.,"yes"),
    water_point_no_further = percent_response(water_point,.,"no_further"),
    water_point_no_none = percent_response(water_point,.,"no_none"),
    tap_sanitize_all = percent_response(tap_sanitize,.,"all"),
    tap_sanitize_some = percent_response(tap_sanitize,.,"some"),
    tap_sanitize_no = percent_response(tap_sanitize,.,"no"),
    tap_sanitize_dk = percent_response(tap_sanitize,.,"dont_know"),
    safety_change_increase = percent_response(safety_change,.,"yes_increase"),
    safety_change_decrease = percent_response(safety_change,.,"yes_decrease"),
    safety_change_no = percent_response(safety_change,.,"no_change"),
    safety_change_dk = percent_response(safety_change,.,"dont_know"),
    covid_coping_1_label = select_percents(covid_coping,1,.,questions,choices,"label"),
    covid_coping_1_pct = select_percents(covid_coping,1,.,questions,choices,"percent"),
    covid_coping_2_label = select_percents(covid_coping,2,.,questions,choices,"label"),
    covid_coping_2_pct = select_percents(covid_coping,2,.,questions,choices,"percent"),
    covid_coping_3_label = select_percents(covid_coping,3,.,questions,choices,"label"),
    covid_coping_3_pct = select_percents(covid_coping,3,.,questions,choices,"percent"),
    mhpss_secondary_1_label = select_percents(mhpss_secondary,1,.,questions,choices,"label"),
    mhpss_secondary_1_pct = select_percents(mhpss_secondary,1,.,questions,choices,"percent"),
    mhpss_secondary_2_label = select_percents(mhpss_secondary,2,.,questions,choices,"label"),
    mhpss_secondary_2_pct = select_percents(mhpss_secondary,2,.,questions,choices,"percent"),
    mhpss_secondary_3_label = select_percents(mhpss_secondary,3,.,questions,choices,"label"),
    mhpss_secondary_3_pct = select_percents(mhpss_secondary,3,.,questions,choices,"percent"),
    vul_sleeping_prop = mean(vul_sleeping_prop,na.rm = T)*100,
    covid_shelter_1_label = select_percents(covid_shelter,1,.,questions,choices,"label"),
    covid_shelter_1_pct = select_percents(covid_shelter,1,.,questions,choices,"percent"),
    covid_shelter_2_label = select_percents(covid_shelter,2,.,questions,choices,"label"),
    covid_shelter_2_pct = select_percents(covid_shelter,2,.,questions,choices,"percent"),
    covid_shelter_3_label = select_percents(covid_shelter,3,.,questions,choices,"label"),
    covid_shelter_3_pct = select_percents(covid_shelter,3,.,questions,choices,"percent"),
    market_soldout_yes = percent_response(market_soldout,.,"yes"),
    market_soldout_no = percent_response(market_soldout,.,"no"),
    market_soldout_dk = percent_response(market_soldout,.,"dont_know"),
    soldout_item_1_label = select_percents(soldout_item,1,.,questions,choices,"label"),
    soldout_item_1_pct = select_percents(soldout_item,1,.,questions,choices,"percent"),
    soldout_item_2_label = select_percents(soldout_item,2,.,questions,choices,"label"),
    soldout_item_2_pct = select_percents(soldout_item,2,.,questions,choices,"percent"),
    soldout_item_3_label = select_percents(soldout_item,3,.,questions,choices,"label"),
    soldout_item_3_pct = select_percents(soldout_item,3,.,questions,choices,"percent"),
    work_change_fullstop = percent_response(work_change,.,"full_stop"),
    work_change_partstop = percent_response(work_change,.,"part_stop"),
    work_change_nostop = percent_response(work_change,.,"no_stop"),
    school_alternatives.other_facility = round(mean(school_alternatives.other_facility,na.rm = T)*100,2),
    school_alternatives.home_school = round(mean(school_alternatives.home_school,na.rm = T)*100,2),
    school_alternatives.other = round(mean(school_alternatives.other,na.rm = T)*100,2),
    school_alternatives.no = round(mean(school_alternatives.no,na.rm = T)*100,2),
    school_alternatives.dont_know = round(mean(school_alternatives.dont_know,na.rm = T)*100,2)
  )
dm_province %>% write_csv("./output/datamerge_province.csv")

dm_district <- parent_created %>%
  group_by(district) %>%
  summarise(
    nb_sites = n(),
    idp_hhs = sum(idp_hhs,na.rm = T),
    idp_indvl =sum(idp_indvl,na.rm = T),
    prolonged_hhs = sum(prolonged_hhs,na.rm = T),
    prolonged_indvl = sum(prolonged_indvl,na.rm = T),
    protracted_hhs = sum(protracted_hhs,na.rm = T),
    protracted_indvl = sum(protracted_indvl, na.rm = T),
    refugee_hhs = sum(refugee_hhs,na.rm = T),
    refugee_indvl = sum(refugee_indvl,na.rm = T),
    returnee_hhs = sum(returnee_hhs,na.rm = T),
    returnee_indvl = sum(returnee_indvl,na.rm = T),
    economic_hhs = sum(economic_hhs,na.rm = T),
    economic_indvl = sum(economic_indvl, na.rm = T),
    nomad_hhs = sum(nomad_hhs, na.rm = T),
    nomad_indvl = sum(nomad_indvl, na.rm = T),
    host_hhs = sum(host_hhs, na.rm = T),
    host_indvl = sum(host_indvl, na.rm = T),
    iset_population_discrete = percent_response(iset_population,.,"discrete"),
    iset_population_mixed = percent_response(iset_population,.,"mixed"),
    location_urban = percent_response(location_fs,.,"urban"),
    location_suburban = percent_response(location_fs,.,"suburb"),
    location_rural = percent_response(location_fs,.,"rural"),
    idp_mixed = round(mean(idp_mixed,na.rm = T)*100,2),
    idp_discrete = round(mean(idp_discrete,na.rm = T)*100,2),
    prolong_mixed = round(mean(prolong_mixed,na.rm = T)*100,2),
    prolong_discrete= round(mean(prolong_discrete,na.rm = T)*100,2),
    protract_mixed=round(mean(protract_mixed,na.rm = T)*100,2),
    protract_discrete=mean(protract_discrete,na.rm = T)*100,
    refugee_mixed= round(mean(refugee_mixed,na.rm = T)*100,2),
    refugee_discrete=mean(refugee_discrete,na.rm = T)*100,
    returnee_mixed=round(mean(returnee_mixed,na.rm = T)*100,2),
    returnee_discrete=round(mean(returnee_discrete,na.rm = T)*100,2),
    economic_mixed=round(mean(economic_mixed,na.rm = T)*100,2),
    economic_discrete=round(mean(economic_discrete,na.rm = T)*100,2),
    nomad_mixed=round(mean(nomad_mixed,na.rm = T)*100,2),
    nomad_discrete=round(mean(nomad_discrete,na.rm = T)*100,2),
    migrant_population.idp = round(mean(migrant_population.idp,na.rm = T)*100,2),
    migrant_population.prolong = round(mean(migrant_population.prolong,na.rm = T)*100,2),
    migrant_population.protract = round(mean(migrant_population.protract,na.rm = T)*100,2),
    migrant_population.refugee = round(mean(migrant_population.refugee,na.rm = T)*100,2),
    migrant_population.returnee = round(mean(migrant_population.returnee,na.rm = T)*100,2),
    relocate_plan_yes = percent_response(relocate_plan,.,"yes"),
    relocate_plan_no = percent_response(relocate_plan,.,"no"),
    relocate_plan_dk = percent_response(relocate_plan,.,"dont_know"),
    relocate_pushpull_1_label = select_percents(relocate_pushpull,1,.,questions,choices,"label"),
    relocate_pushpull_1_pct = select_percents(relocate_pushpull,1,.,questions,choices,"percent"),
    relocate_pushpull_2_label = select_percents(relocate_pushpull,2,.,questions,choices,"label"),
    relocate_pushpull_2_pct = select_percents(relocate_pushpull,2,.,questions,choices,"percent"),
    relocate_pushpull_3_label = select_percents(relocate_pushpull,3,.,questions,choices,"label"),
    relocate_pushpull_3_pct = select_percents(relocate_pushpull,3,.,questions,choices,"percent"),
    five_years_yes = percent_response(five_years,.,"yes"),
    five_years_no = percent_response(five_years,.,"no"),
    five_years_dk = percent_response(five_years,.,"dont_know"),
    idp_3mo_hhs = sum(idp_3mo_hhs,na.rm = T),
    idp_prov_origin_1_label = select_percents(idp_prov_origin,1,.,questions,choices,"label"),
    idp_prov_origin_1_pct = select_percents(idp_prov_origin,1,.,questions,choices,"percent"),
    idp_prov_origin_2_label = select_percents(idp_prov_origin,2,.,questions,choices,"label"),
    idp_prov_origin_2_pct = select_percents(idp_prov_origin,2,.,questions,choices,"percent"),
    idp_prov_origin_3_label = select_percents(idp_prov_origin,3,.,questions,choices,"label"),
    idp_prov_origin_3_pct = select_percents(idp_prov_origin,3,.,questions,choices,"percent"),
    returnee_3mo_hhs = sum(returnee_3mo_hhs,na.rm = T),
    returnee_origin_1_label = select_percents(returnee_origin,1,.,questions,choices,"label"),
    returnee_origin_1_pct = select_percents(returnee_origin,1,.,questions,choices,"percent"),
    returnee_origin_2_label = select_percents(returnee_origin,2,.,questions,choices,"label"),
    returnee_origin_2_pct = select_percents(returnee_origin,2,.,questions,choices,"percent"),
    returnee_origin_3_label = select_percents(returnee_origin,3,.,questions,choices,"label"),
    returnee_origin_3_pct = select_percents(returnee_origin,3,.,questions,choices,"percent"),
    shelter_type_1_label = select_percents(shelter_type,1,.,questions,choices,"label"),
    shelter_type_1_pct = select_percents(shelter_type,1,.,questions,choices,"percent"),
    shelter_type_2_label = select_percents(shelter_type,2,.,questions,choices,"label"),
    shelter_type_2_pct = select_percents(shelter_type,2,.,questions,choices,"percent"),
    shelter_type_3_label = select_percents(shelter_type,3,.,questions,choices,"label"),
    shelter_type_3_pct = select_percents(shelter_type,3,.,questions,choices,"percent"),
    tenure_insecure = percent_response(tenure_insecure,.,"yes"),
    hh_rooms = mean(hh_rooms,na.rm = T),
    accom_1_label = select_percents(accom,1,.,questions,choices,"label"),
    accom_1_pct = select_percents(accom,1,.,questions,choices,"percent"),
    accom_2_label = select_percents(accom,2,.,questions,choices,"label"),
    accom_2_pct = select_percents(accom,2,.,questions,choices,"percent"),
    accom_3_label = select_percents(accom,3,.,questions,choices,"label"),
    accom_3_pct = select_percents(accom,3,.,questions,choices,"percent"),
    host_relation_positive = percent_response(host_relation,.,"positive"),
    host_relation_neutral = percent_response(host_relation,.,"neutral"),
    host_relation_negative = percent_response(host_relation,.,"negative"),
    host_relation_prefer_not = percent_response(host_relation,.,"prefer_not"),
    eviction_threat_yes = percent_response(eviction_threat,.,"yes"),
    eviction_threat_no = percent_response(eviction_threat,.,"no"),
    eviction_threat_dk = percent_response(eviction_threat,.,"dont_know"),
    eviction_threat_local_auth = round(mean(eviction_threat_why.local_auth,na.rm = T)*100,2),
    eviction_threat_gvt = round(mean(eviction_threat_why.government,na.rm = T)*100,2),
    eviction_threat_local_host_comm = round(mean(eviction_threat_why.host_comm,na.rm = T)*100,2),
    eviction_threat_local_ot = round(mean(eviction_threat_why.other,na.rm = T)*100,2),
    comm_represent_yes = percent_response(comm_represent,.,"yes"),
    comm_represent_no = percent_response(comm_represent,.,"no"),
    comm_represent_dk = percent_response(comm_represent,.,"dont_know"),
    relocation_yes = percent_response(relocation,.,"yes"),
    relocation_no = percent_response(relocation,.,"no"),
    site_land_yes = percent_response(site_land,.,"yes"),
    site_land_no = percent_response(site_land,.,"no"),
    site_land_dk = percent_response(site_land,.,"dont_know"),
    site_land_owner_gvt = percent_response(site_land_owner,.,"government"),
    site_land_owner_prv = percent_response(site_land_owner,.,"private"),
    site_land_owner_un = percent_response(site_land_owner,.,"un"),
    site_land_owner_common = percent_response(site_land_owner,.,"common"),
    site_land_owner_ot = percent_response(site_land_owner,.,"other"),
    water_distance_fs = percent_response(water_distance_fs,.,"yes"),
    water_source_fs = mean(water_source_fs,na.rm = T),
    water_barrier_1_label = select_percents(water_barrier,1,.,questions,choices,"label"),
    water_barrier_1_pct = select_percents(water_barrier,1,.,questions,choices,"percent"),
    water_barrier_2_label = select_percents(water_barrier,2,.,questions,choices,"label"),
    water_barrier_2_pct = select_percents(water_barrier,2,.,questions,choices,"percent"),
    water_barrier_3_label = select_percents(water_barrier,3,.,questions,choices,"label"),
    water_barrier_3_pct = select_percents(water_barrier,3,.,questions,choices,"percent"),
    health_distance_fs = percent_response(health_distance_fs,.,"yes"),
    health_satisfy_constraint_yes = percent_response(health_satisfy_constraint,.,"yes"),
    health_satisfy_constraint_no = percent_response(health_satisfy_constraint,.,"no"),
    health_satisfy_constraint_dk = percent_response(health_satisfy_constraint,.,"dont_know"),
    health_unsatisfy_constraint.crowded = round(mean(health_unsatisfy_constraint.crowded,na.rm = T)*100,2),
    health_unsatisfy_constraint.hours = round(mean(health_unsatisfy_constraint.hours,na.rm = T)*100,2),
    health_unsatisfy_constraint.expensive = round(mean(health_unsatisfy_constraint.expensive,na.rm = T)*100,2),
    health_unsatisfy_constraint.drug_unavail = round(mean(health_unsatisfy_constraint.drug_unavail,na.rm = T)*100,2),
    health_unsatisfy_constraint.staff_behave = round(mean(health_unsatisfy_constraint.staff_behave,na.rm = T)*100,2),
    health_unsatisfy_constraint.other = round(mean(health_unsatisfy_constraint.other,na.rm = T)*100,2),
    health_unsatisfy_constraint.dont_know = round(mean(health_unsatisfy_constraint.dont_know,na.rm = T)*100,2),
    mhpss_aware_yes = percent_response(mhpss_aware,.,"yes"),
    mhpss_aware_no = percent_response(mhpss_aware,.,"no"),
    mhpss_aware_dk = percent_response(mhpss_aware,.,"dont_know"),
    health_barrier_1_label = select_percents(health_barrier,1,.,questions,choices,"label"),
    health_barrier_1_pct = select_percents(health_barrier,1,.,questions,choices,"percent"),
    health_barrier_2_label = select_percents(health_barrier,2,.,questions,choices,"label"),
    health_barrier_2_pct = select_percents(health_barrier,2,.,questions,choices,"percent"),
    health_barrier_3_label = select_percents(health_barrier,3,.,questions,choices,"label"),
    health_barrier_3_pct = select_percents(health_barrier,3,.,questions,choices,"percent"),
    safe_likert_verygood = percent_response(safe_likert,.,"very_good"),
    safe_likert_good = percent_response(safe_likert,.,"good"),
    safe_likert_neutral = percent_response(safe_likert,.,"neutral"),
    safe_likert_poor = percent_response(safe_likert,.,"poor_qual"),
    safe_likert_verypoor = percent_response(safe_likert,.,"very_poor"),
    move_free_m_yes = percent_response(move_free_m,.,"yes"),
    move_free_m_no = percent_response(move_free_m,.,"no"),
    move_free_m_dk = percent_response(move_free_m,.,"dont_know"),
    move_why_m_1_label = select_percents(move_why_m,1,.,questions,choices,"label"),
    move_why_m_1_pct = select_percents(move_why_m,1,.,questions,choices,"percent"),
    move_why_m_2_label = select_percents(move_why_m,2,.,questions,choices,"label"),
    move_why_m_2_pct = select_percents(move_why_m,2,.,questions,choices,"percent"),
    move_why_m_3_label = select_percents(move_why_m,3,.,questions,choices,"label"),
    move_why_m_3_pct = select_percents(move_why_m,3,.,questions,choices,"percent"),
    move_free_f_yes = percent_response(move_free_f,.,"yes"),
    move_free_f_no = percent_response(move_free_f,.,"no"),
    move_free_f_dk = percent_response(move_free_f,.,"dont_know"),
    move_why_f_1_label = select_percents(move_why_f,1,.,questions,choices,"label"),
    move_why_f_1_pct = select_percents(move_why_f,1,.,questions,choices,"percent"),
    move_why_f_2_label = select_percents(move_why_f,2,.,questions,choices,"label"),
    move_why_f_2_pct = select_percents(move_why_f,2,.,questions,choices,"percent"),
    move_why_f_3_label = select_percents(move_why_f,3,.,questions,choices,"label"),
    move_why_f_3_pct = select_percents(move_why_f,3,.,questions,choices,"percent"),
    livelihood_1_label = select_percents(livelihood,1,.,questions,choices,"label"),
    livelihood_1_pct = select_percents(livelihood,1,.,questions,choices,"percent"),
    livelihood_2_label = select_percents(livelihood,2,.,questions,choices,"label"),
    livelihood_2_pct = select_percents(livelihood,2,.,questions,choices,"percent"),
    livelihood_3_label = select_percents(livelihood,3,.,questions,choices,"label"),
    livelihood_3_pct = select_percents(livelihood,3,.,questions,choices,"percent"),
    food_source_1_label = select_percents(food_source,1,.,questions,choices,"label"),
    food_source_1_pct = select_percents(food_source,1,.,questions,choices,"percent"),
    food_source_2_label = select_percents(food_source,2,.,questions,choices,"label"),
    food_source_2_pct = select_percents(food_source,2,.,questions,choices,"percent"),
    food_source_3_label = select_percents(food_source,3,.,questions,choices,"label"),
    food_source_3_pct = select_percents(food_source,3,.,questions,choices,"percent"),
    vul_index_low = percent_response(vulnerability_classification,.,"lower_risk"),
    vul_index_moderate = percent_response(vulnerability_classification,.,"moderate_risk"),
    vul_index_moderate_high = percent_response(vulnerability_classification,.,"moderate_high_risk"),
    vul_index_high = percent_response(vulnerability_classification,.,"higher_risk"),
    covid_aware_yes = percent_response(covid_aware,.,"yes"),
    covid_aware_part = percent_response(covid_aware,.,"part"),
    covid_aware_no = percent_response(covid_aware,.,"no"),
    covid_concern_yes = percent_response(covid_concern,.,"yes"),
    covid_concern_no = percent_response(covid_concern,.,"no"),
    covid_concern_dk = percent_response(covid_concern,.,"dont_know"),
    covid_info_1_label = select_percents(covid_info,1,.,questions,choices,"label"),
    covid_info_1_pct = select_percents(covid_info,1,.,questions,choices,"percent"),
    covid_info_2_label = select_percents(covid_info,2,.,questions,choices,"label"),
    covid_info_2_pct = select_percents(covid_info,2,.,questions,choices,"percent"),
    covid_info_3_label = select_percents(covid_info,3,.,questions,choices,"label"),
    covid_info_3_pct = select_percents(covid_info,3,.,questions,choices,"percent"),
    covid_safeprac_1_label = select_percents(covid_safeprac,1,.,questions,choices,"label"),
    covid_safeprac_1_pct = select_percents(covid_safeprac,1,.,questions,choices,"percent"),
    covid_safeprac_2_label = select_percents(covid_safeprac,2,.,questions,choices,"label"),
    covid_safeprac_2_pct = select_percents(covid_safeprac,2,.,questions,choices,"percent"),
    covid_safeprac_3_label = select_percents(covid_safeprac,3,.,questions,choices,"label"),
    covid_safeprac_3_pct = select_percents(covid_safeprac,3,.,questions,choices,"percent"),
    aid_govt_yes = percent_response(aid_govt,.,"yes"),
    aid_govt_no = percent_response(aid_govt,.,"no"),
    aid_govt_dk = percent_response(aid_govt,.,"dont_know"),
    aid_services_1_label = select_percents(aid_services,1,.,questions,choices,"label"),
    aid_services_1_pct = select_percents(aid_services,1,.,questions,choices,"percent"),
    aid_services_2_label = select_percents(aid_services,2,.,questions,choices,"label"),
    aid_services_2_pct = select_percents(aid_services,2,.,questions,choices,"percent"),
    aid_services_3_label = select_percents(aid_services,3,.,questions,choices,"label"),
    aid_services_3_pct = select_percents(aid_services,3,.,questions,choices,"percent"),
    vul_chronic_fs = mean(vul_chronic_fs,na.rm = T)*100,
    soap_avail_yes = percent_response(soap_avail,.,"yes"),
    soap_avail_no = percent_response(soap_avail,.,"no"),
    soap_avail_dk = percent_response(soap_avail,.,"dont_know"),
    using_public_facility = mean(using_public_facility,na.rm = T)* 100,
    handwash_crowded_yes = percent_response(handwash_crowded,.,"yes"),
    handwash_crowded_no = percent_response(handwash_crowded,.,"no"),
    handwash_crowded_dk = percent_response(handwash_crowded,.,"dont_know"),
    water_point_yes = percent_response(water_point,.,"yes"),
    water_point_no_further = percent_response(water_point,.,"no_further"),
    water_point_no_none = percent_response(water_point,.,"no_none"),
    tap_sanitize_all = percent_response(tap_sanitize,.,"all"),
    tap_sanitize_some = percent_response(tap_sanitize,.,"some"),
    tap_sanitize_no = percent_response(tap_sanitize,.,"no"),
    tap_sanitize_dk = percent_response(tap_sanitize,.,"dont_know"),
    safety_change_increase = percent_response(safety_change,.,"yes_increase"),
    safety_change_decrease = percent_response(safety_change,.,"yes_decrease"),
    safety_change_no = percent_response(safety_change,.,"no_change"),
    safety_change_dk = percent_response(safety_change,.,"dont_know"),
    covid_coping_1_label = select_percents(covid_coping,1,.,questions,choices,"label"),
    covid_coping_1_pct = select_percents(covid_coping,1,.,questions,choices,"percent"),
    covid_coping_2_label = select_percents(covid_coping,2,.,questions,choices,"label"),
    covid_coping_2_pct = select_percents(covid_coping,2,.,questions,choices,"percent"),
    covid_coping_3_label = select_percents(covid_coping,3,.,questions,choices,"label"),
    covid_coping_3_pct = select_percents(covid_coping,3,.,questions,choices,"percent"),
    mhpss_secondary_1_label = select_percents(mhpss_secondary,1,.,questions,choices,"label"),
    mhpss_secondary_1_pct = select_percents(mhpss_secondary,1,.,questions,choices,"percent"),
    mhpss_secondary_2_label = select_percents(mhpss_secondary,2,.,questions,choices,"label"),
    mhpss_secondary_2_pct = select_percents(mhpss_secondary,2,.,questions,choices,"percent"),
    mhpss_secondary_3_label = select_percents(mhpss_secondary,3,.,questions,choices,"label"),
    mhpss_secondary_3_pct = select_percents(mhpss_secondary,3,.,questions,choices,"percent"),
    vul_sleeping_prop = mean(vul_sleeping_prop,na.rm = T)*100,
    covid_shelter_1_label = select_percents(covid_shelter,1,.,questions,choices,"label"),
    covid_shelter_1_pct = select_percents(covid_shelter,1,.,questions,choices,"percent"),
    covid_shelter_2_label = select_percents(covid_shelter,2,.,questions,choices,"label"),
    covid_shelter_2_pct = select_percents(covid_shelter,2,.,questions,choices,"percent"),
    covid_shelter_3_label = select_percents(covid_shelter,3,.,questions,choices,"label"),
    covid_shelter_3_pct = select_percents(covid_shelter,3,.,questions,choices,"percent"),
    market_soldout_yes = percent_response(market_soldout,.,"yes"),
    market_soldout_no = percent_response(market_soldout,.,"no"),
    market_soldout_dk = percent_response(market_soldout,.,"dont_know"),
    soldout_item_1_label = select_percents(soldout_item,1,.,questions,choices,"label"),
    soldout_item_1_pct = select_percents(soldout_item,1,.,questions,choices,"percent"),
    soldout_item_2_label = select_percents(soldout_item,2,.,questions,choices,"label"),
    soldout_item_2_pct = select_percents(soldout_item,2,.,questions,choices,"percent"),
    soldout_item_3_label = select_percents(soldout_item,3,.,questions,choices,"label"),
    soldout_item_3_pct = select_percents(soldout_item,3,.,questions,choices,"percent"),
    work_change_fullstop = percent_response(work_change,.,"full_stop"),
    work_change_partstop = percent_response(work_change,.,"part_stop"),
    work_change_nostop = percent_response(work_change,.,"no_stop"),
    school_alternatives.other_facility = round(mean(school_alternatives.other_facility,na.rm = T)*100,2),
    school_alternatives.home_school = round(mean(school_alternatives.home_school,na.rm = T)*100,2),
    school_alternatives.other = round(mean(school_alternatives.other,na.rm = T)*100,2),
    school_alternatives.no = round(mean(school_alternatives.no,na.rm = T)*100,2),
    school_alternatives.dont_know = round(mean(school_alternatives.dont_know,na.rm = T)*100,2)
  )
dm_district %>% write_csv("./output/datamerge_district.csv")
